apiVersion: v1
kind: ConfigMap
metadata: 
  name: kubecoin-config
  labels:
    app: kubecoin
  namespace: testing
data: 
  POSTGRES_DB: "kubecoin"
  DB_HOST: "postgres-headless"
  DB_NAME: "kubecoin"
  BACKEND_URL: "http://backend-service.testing.svc.cluster.local:5000"
