apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: postgres-pvc
  labels:
    app: postgres
  namespace: production
spec:
  volumeName: postgres-pv-production
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
