apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: postgres-pvc-production
  labels:
    app: postgres
    env: production
  namespace: production
spec:
  volumeName: postgres-pv-production
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
