apiVersion: v1
kind: ResourceQuota
metadata: 
  name: production-quota
  namespace: production
spec:
  hard:
    pods: "6"
    requests.cpu: "1500m"
    limits.cpu: "2"
    requests.memory: 1.5Gi
    limits.memory: 1.8Gi
