apiVersion: v1
kind: ResourceQuota
metadata: 
  name: testing-quota
  namespace: testing
spec:
  hard:
    pods: "6"
    requests.cpu: "500m"
    limits.cpu: "1"
    requests.memory: 512Mi
    limits.memory: 1Gi
